Plugins/MVC/Aspose.MVC.ExportContentToImages/ExportContentToImages/Controllers/ExportToImageController.cs
using System;
using System.IO;
using System.IO.Compression;
using System.Net;
using System.Web.Mvc;
using Aspose.Words;
using System.Text;
using Aspose.Words.Saving;

namespace ExportContentToImages.Controllers
{
    public class ExportToImageController : Controller
    {
        // GET: /ExportToImage/
        public ActionResult Index(string Format="png")
        {
            // License this component using an Aspose.Words license file,
            // if one exists at this location in the local file system.
            string licenseFile = Server.MapPath("~/App_Data/Aspose.Words.lic");

            if (System.IO.File.Exists(licenseFile))
            {
                License license = new License();
                license.SetLicense(licenseFile);
            }

            if (Request.UrlReferrer == null) 
                return RedirectToAction("index", "Home");

            string refUrl = Request.UrlReferrer.AbsoluteUri;
            string html = new WebClient().DownloadString(refUrl);

            Document doc;

            using (MemoryStream memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(html)))
            {
                doc = new Document(memoryStream);
            }

            string imageFileName = "";

            if (doc.PageCount > 1)
                Directory.CreateDirectory(Server.MapPath("~/Images/" + "Zip"));

            ImageSaveOptions options = new ImageSaveOptions(SaveFormat.Png);

            if (Format.Contains("png"))
            {
                options = new ImageSaveOptions(SaveFormat.Png);
                options.PageSet = new PageSet(0);
            }
            else if (Format.Contains("JPEG"))
            {
                options = new ImageSaveOptions(SaveFormat.Jpeg);
                options.PageSet = new PageSet(0);
            }
            else if (Format.Contains("TIFF"))
            {
                options = new ImageSaveOptions(SaveFormat.Tiff);
                options.PageSet = new PageSet(0);
            }
            else if (Format.Contains("bmp"))
            {
                options = new ImageSaveOptions(SaveFormat.Bmp);
                options.PageSet = new PageSet(0);
            }

            // Create an "Images" folder, and populate it with images that we will render the document into.
            string imageFolderPath = Server.MapPath("~/Images");

            if (!Directory.Exists(imageFolderPath))
                Directory.CreateDirectory(imageFolderPath);


            for (int i = 0; i < doc.PageCount; i++)
            {
                imageFileName = $"{i}_{Guid.NewGuid()}.{Format}";;

                if (Format.Contains("TIFF"))
                {
                    options.PageSet = PageSet.All;
                    doc.Save(Server.MapPath("~/Images/Zip/") + imageFileName, options);
                }
                else
                {
                    options.PageSet = new PageSet(i);

                    if (doc.PageCount > 1)
                        doc.Save(Server.MapPath("~/Images/Zip/") + imageFileName, options);
                    else
                        doc.Save(Server.MapPath("~/Images/Zip/") + imageFileName, options);
                }
            }

            // If a webpage is large enough for multiple images, and the output image type is not "Tiff",
            // then download them all in one Zip. A single Tiff file will contain
            // all the images, so we do not need a Zip archive in this case.
            if (doc.PageCount > 1 && !Format.Contains("TIFF"))
            {
                string ImagePath = Server.MapPath("~/Images/Zip/");
                string downloadDirectory = Server.MapPath("~/Images/");
                ZipFile.CreateFromDirectory(ImagePath, downloadDirectory + "OutputImages.zip");

                System.Web.HttpResponse response = System.Web.HttpContext.Current.Response;
                response.ClearContent();
                response.Clear();
                response.ContentType = "application/zip";
                response.AddHeader("Content-Disposition", "attachment; filename=OutputImages.zip" + ";");
                response.TransmitFile(downloadDirectory + "OutputImages.zip");
                response.End();

                Directory.Delete(ImagePath, true);
                System.IO.File.Delete(downloadDirectory + "OutputImages.zip");
            }
            else
            {
                string filepath = Server.MapPath("~/Images/Zip/") + imageFileName;
                string downloadDirectory = Server.MapPath("~/Images/Zip/");
                System.Web.HttpResponse response = System.Web.HttpContext.Current.Response;

                response.ClearContent();
                response.Clear();
                response.ContentType = "image/"+Format;
                response.AddHeader("Content-Disposition", "attachment; filename="+imageFileName + ";");
                response.TransmitFile(filepath);
                response.End();

                Directory.Delete(downloadDirectory, true);
            }

            return RedirectToAction("index", "Home");
        }
    }
}

Plugins/MVC/Aspose.MVC.ExportContentToImages/ExportContentToImages/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ExportContentToImages.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }
    }
}

Plugins/MVC/Aspose.MVC.ExportContentToImages/ExportContentToImages/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Aspose.Words for ASP.NET MVC";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>

.tbl
{
border:0;
width:100%;
}


.tbl2
{
height: 65px;
width:590px;    
}

.tblImage
{
padding-left: 8px; 
vertical-align: middle;   
}

.tblBackground
{
    background-color: #f0f1f4;   
}

.setSize
{
width:60px;
height:60px;  
}

</style>



<h2>Welcome to Aspose.Words for ASP.NET MVC</h2>
@{ Html.RenderPartial("~/Views/Shared/AsposeContentToImage.cshtml"); }

<div class="wikidoc">
    <strong>Specializing in:</strong>&nbsp;BMP, JPEG, TIFF, GIF, PNG and PSD images
    <p><br /> This project contains Plugins, Controls and example code that will help you to write your own application using <a href="http://www.aspose.com/.net/word-component.aspx">Aspose.Words for .NET</a>. Following is short description of contents of the repository:</p>
    <table class="tbl2">
        <thead>
            <tr>
                <td class="tblBackground"><strong>Directory</strong></td>
                <td class="tblBackground"><strong>Description</strong></td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong><a href="https://asposewordsnetmvc.codeplex.com/documentation">Plugins</a></strong></td>
                <td>Standalone Plugins that will demonstrate one or multiple features of Aspose.Words for .NET</td>
            </tr>
        </tbody>
    </table>

    <h2>Resources</h2>
    <ul>
        <li><strong>Website:</strong>&nbsp;<a href="http://www.aspose.com/">www.aspose.com</a></li>
        <li><strong>Product Home:</strong>&nbsp;<a href="http://www.aspose.com/.net/word-component.aspx">Aspose.Words for .NET</a></li>
        <li><strong>Download:</strong>&nbsp;<a href="http://www.aspose.com/community/files/51/.net-components/aspose.words-for-.net/default.aspx">Download Aspose.Words for .NET</a></li>
        <li><strong>Documentation:</strong>&nbsp;<a href="http://www.aspose.com/docs/display/wordsnet/Home">Aspose.Words for .NET Documentation</a></li>
        <li><strong>Forum:</strong>&nbsp;<a href="http://www.aspose.com/community/forums/aspose.words-product-family/75/showforum.aspx">Aspose.Words for .NET Forum</a></li>
        <li><strong>Blog:</strong>&nbsp;<a href="http://www.aspose.com/blogs/aspose-products/aspose-words-product-family.html">Aspose.Words for .NET Blog</a></li>
    </ul>
    <h2>What is the use of Aspose .NET Products?</h2>
    <p><a href="http://www.aspose.com">Aspose</a> are file format experts and provide APIs and components for various file formats including MS Office, OpenOffice, PDF and Image formats. These APIs are available on a number of development platforms including .NET frameworks &ndash; the .NET frameworks starting from version 2.0 are supported. If you are a .NET developer, you can use Aspose&rsquo;s native .NET APIs in your .NET applications to process various file formats in just a few lines of codes. All the Aspose APIs don&rsquo;t have any dependency over any other engine. For example, you don&rsquo;t need to have MS Office installed on the server to process MS Office files. Below is a list of products we support for .NET developers:</p>
</div>
<table class="tbl">
    <tbody>
        <tr>
            <td><a href="http://www.aspose.com/.net/excel-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_cells-for-net.jpg" alt="Aspose.Cells for .NET" class="setSize" /></a></td>
            <td class="tblImage"><a href="http://www.aspose.com/.net/excel-component.aspx"><strong>Aspose.Cells for .NET</strong></a> <br /> <strong>Specializing in:</strong> XLS, XLSX, XLSM, SpreadsheetML, CSV, Tab Delimited, ODS, HTML, PDF documents</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/word-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_words-for-net.jpg" alt="Aspose.Words for .NET" class="setSize" /></a></td>
            <td class="tblImage">
                <p style="text-align: left;"><a href="http://www.aspose.com/.net/word-component.aspx"><strong>Aspose.Words for .NET</strong></a><br /> <strong>Specializing in:</strong> DOC, DOCX, RTF, FlatOpc, WordML, XML, ODT, TXT, HTML files</p>
            </td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/pdf-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_pdf-for-net.jpg" alt="Aspose.PDF for .NET" class="setSize" /></a></td>
            <td class="tblImage"><a href="http://www.aspose.com/.net/pdf-component.aspx"><strong>Aspose.Pdf for .NET</strong></a><br /> <strong>Specializing in:</strong> PDF, PDF/A</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/powerpoint-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_slides-for-net.jpg" alt="Aspose.Slides for .NET" class="setSize" /></a></td>
            <td class="tblImage"><a href="http://www.aspose.com/.net/powerpoint-component.aspx"><strong>Aspose.Slides for .NET</strong></a><br /> <strong>Specializing in:</strong> PPT, POT, PPS, PPTX, POTX, PPSX, ODP, PDF, PDF Notes, XPS, SVG, TIFF and HTML files.</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/barcode-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_barcode-for-net.jpg" alt="Aspose.BarCode for .NET" class="setSize" /></a></td>
            <td class="tblImage"><a href="http://www.aspose.com/.net/barcode-component.aspx"><strong>Aspose.BarCode for .NET</strong></a> <br /> <strong>Specializing in:</strong> Creating and reading (generating and recognizing) over 25 types of the most popular linear, 2D and postal barcode symbologies</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/project-management-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_tasks-for-net.jpg" alt="Aspose.Tasks for .NET" class="setSize" /></a></td>
            <td class="tblImage"><a href="http://www.aspose.com/.net/project-management-component.aspx"><strong>Aspose.Tasks for .NET</strong></a><br /> <strong>Specializing in:</strong> MSG, OFT, MHT, EML, EMLX, PST and OST files, and communication with Microsoft Exchange</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/email-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_email-for-net.jpg" alt="Aspose.Email for .NET" class="setSize" /></a></td>
            <td class="tblImage"><a href="http://www.aspose.com/.net/email-component.aspx"><strong>Aspose.Email for .NET</strong></a><br /> <strong>Specializing in:</strong> MPP/XML, Microsoft Project (2003, 2007, 2010, 2013)</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/diagram-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_diagram-for-net.jpg" alt="Aspose.Diagram for .NET" class="setSize" /></a></td>
            <td class="tblImage"><a href="http://www.aspose.com/.net/diagram-component.aspx"><strong>Aspose.Diagram for .NET</strong></a> <br /> <strong>Specializing in:</strong> VSD/VDX, Microsoft Visio (2007/2010/2013)</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/ocr-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_ocr-for-net.jpg" alt="Aspose.OCR for .NET" class="setSize" /></a></td>
            <td class="tblImage"><a href="http://www.aspose.com/.net/ocr-component.aspx"><strong>Aspose.OCR for .NET</strong></a> <br /> <strong>Specializing in:</strong> Extracting text from images</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/imaging-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_imaging-for-net.jpg" alt="Aspose.Imaging for .NET" class="setSize" /> </a></td>
            <td class="tblImage"><a href="http://www.aspose.com/.net/imaging-component.aspx"><strong>Aspose.Imaging for .NET</strong></a> <br /> <strong>Specializing in:</strong> BMP, JPEG, TIFF, GIF, PNG and PSD images</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/imaging-component.aspx"><img src="http://cdn.aspose.com/images/marketplace/aspose_note-for-net.png" alt="Aspose.Imaging for .NET" class="setSize" /> </a></td>
            <td class="tblImage"><a href="http://www.aspose.com/.net/imaging-component.aspx"><strong>Aspose.Note for .NET</strong></a> <br /> <strong>Specializing in:</strong> Microsoft OneNote (2010/2013)</td>
        </tr>
    </tbody>
</table>

Plugins/MVC/Aspose.MVC.ExportContentToImages/ExportContentToImages/Views/Shared/AsposeContentToImage.cshtml
<style>
    .setDiv {
        display: flex;
    }
</style>
<div class="setDiv">
    <select id="AsposeContentExportImagesTypes" class="form-control">
        <option value="">Select an Export Format</option>
        <option value="JPEG">JPEG Image format (*.jpeg)</option>
        <option value="PNG">PNG Image format (*.png)</option>
        <option value="BMP">BMP Image format (*.bmp)</option>
        <option value="TIFF">TIFF Image format (*.tiff)</option>
    </select>
    <div class="Padding">
        <a class="btn btn-primary" onclick=" redirect(); ">Export To Image</a>
    </div>
</div>

<script type="text/javascript">
    var result = "";

    document.getElementById('AsposeContentExportImagesTypes').onchange = function ()
    {
        result = this.value;
    }



    function redirect() {

        
        if (result != '') {
            window.location.href = '@Url.Action("Index", "ExportToImage")/' + '?format=' + result;
        } else {
            alert("Please Select Export Format");
        }
    }


    
</script>




 

Plugins/MVC/Aspose.MVC.ExportContentToImages/ExportContentToImages/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" type="text/css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>
    @RenderSection("head", false)
</head>
<body>
    <div class="container-fluid">
        @RenderBody()
    </div>
</body>
</html>