Plugins/MVC/Aspose.MVC.ExportToWord/Controllers/ExportToWordController.cs
using Aspose.Words;
using System;
using System.IO;
using System.Net;
using System.Text;
using System.Web.Mvc;

namespace Aspose.MVC.ExportToWord.Controllers
{
    public class ExportToWordController : Controller
    {
        // GET: /ExportToWord/
        public void Index()
        {
            ApplyLicense();

            string baseUrl = Request.Url.Authority;
            baseUrl = Request.ServerVariables["HTTPS"] == "on" ? "https://" + baseUrl : "http://" + baseUrl;
            
            string refUrl = Request.UrlReferrer.AbsoluteUri;
            string html = new WebClient().DownloadString(refUrl);

            // To make the relative image paths work, the head section must include the base URL.
            html = html.Replace("</head>", string.Format("<base href='{0}'></base></head>", baseUrl));

            MemoryStream stream = new MemoryStream(Encoding.UTF8.GetBytes(html));
            Document doc = new Document(stream);
            string fileName = Guid.NewGuid() + ".doc";
            doc.Save(System.Web.HttpContext.Current.Response, fileName, ContentDisposition.Inline, null);

            System.Web.HttpContext.Current.Response.End();
        }

        private void ApplyLicense()
        {
            string licenseFile = Server.MapPath("~/App_Data/Aspose.Words.lic");
            if (System.IO.File.Exists(licenseFile))
            {
                License license = new License();
                license.SetLicense(licenseFile);
            }
        }
    }
}

Plugins/MVC/Aspose.MVC.ExportToWord/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Aspose.Words;
using System.IO;
using System.Text;

namespace Aspose.MVC.ExportToWord.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }
        
    }
}

Plugins/MVC/Aspose.MVC.ExportToWord/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Aspose.Words for ASP.NET MVC";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome to Aspose.Words for ASP.NET MVC</h2>
<a class="btn btn-primary pull-right" href="@Url.Action("Index","ExportToWord")">Export To Word</a>
<div class="wikidoc">
    <strong>Specializing in:</strong>&nbsp;DOC, DOCX, OOXML, RTF, HTML, OpenDocument, PDF, XPS, EPUB and other formats
    <p><br /> This project contains Plugins, Controls and example code that will help you to write your own application using <a href="http://www.aspose.com/.net/word-component.aspx">Aspose.Words for .NET</a>. Following is short description of contents of the repository:</p>
    <table style="height: 65px;" width="590">
        <thead>
            <tr>
                <td style="background-color: #f0f1f4;"><strong>Directory</strong></td>
                <td style="background-color: #f0f1f4;"><strong>Description</strong></td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong><a href="https://asposewordsnetmvc.codeplex.com/documentation">Plugins</a></strong></td>
                <td>Standalone Plugins that will demonstrate one or multiple features of Aspose.Words for .NET</td>
            </tr>
        </tbody>
    </table>
    
    <h2>Resources</h2>
    <ul>
        <li><strong>Website:</strong>&nbsp;<a href="http://www.aspose.com/">www.aspose.com</a></li>
        <li><strong>Product Home:</strong>&nbsp;<a href="http://www.aspose.com/.net/word-component.aspx">Aspose.Words for .NET</a></li>
        <li><strong>Download:</strong>&nbsp;<a href="http://www.aspose.com/community/files/51/.net-components/aspose.words-for-.net/default.aspx">Download Aspose.Words for .NET</a></li>
        <li><strong>Documentation:</strong>&nbsp;<a href="http://www.aspose.com/docs/display/wordsnet/Home">Aspose.Words for .NET Documentation</a></li>
        <li><strong>Forum:</strong>&nbsp;<a href="http://www.aspose.com/community/forums/aspose.words-product-family/75/showforum.aspx">Aspose.Words for .NET Forum</a></li>
        <li><strong>Blog:</strong>&nbsp;<a href="http://www.aspose.com/blogs/aspose-products/aspose-words-product-family.html">Aspose.Words for .NET Blog</a></li>
    </ul>
    <h2>What is the use of Aspose .NET Products?</h2>
    <p><a href="http://www.aspose.com">Aspose</a> are file format experts and provide APIs and components for various file formats including MS Office, OpenOffice, PDF and Image formats. These APIs are available on a number of development platforms including .NET frameworks &ndash; the .NET frameworks starting from version 2.0 are supported. If you are a .NET developer, you can use Aspose&rsquo;s native .NET APIs in your .NET applications to process various file formats in just a few lines of codes. All the Aspose APIs don&rsquo;t have any dependency over any other engine. For example, you don&rsquo;t need to have MS Office installed on the server to process MS Office files. Below is a list of products we support for .NET developers:</p>
</div>
<table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tbody>
        <tr>
            <td><a href="http://www.aspose.com/.net/excel-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_cells-for-net.jpg" alt="Aspose.Cells for .NET" width="60" height="60" /></a></td>
            <td style="padding-left: 8px; vertical-align: top;"><a href="http://www.aspose.com/.net/excel-component.aspx"><strong>Aspose.Cells for .NET</strong></a> <br /> <strong>Specializing in:</strong> XLS, XLSX, XLSM, SpreadsheetML, CSV, Tab Delimited, ODS, HTML, PDF documents</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/word-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_words-for-net.jpg" alt="Aspose.Words for .NET" width="60" height="60" /></a></td>
            <td style="padding-left: 8px; vertical-align: top;">
                <p style="text-align: left;"><a href="http://www.aspose.com/.net/word-component.aspx"><strong>Aspose.Words for .NET</strong></a><br /> <strong>Specializing in:</strong> DOC, DOCX, RTF, FlatOpc, WordML, XML, ODT, TXT, HTML files</p>
            </td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/pdf-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_pdf-for-net.jpg" alt="Aspose.PDF for .NET" width="60" height="60" /></a></td>
            <td style="padding-left: 8px; vertical-align: top;"><a href="http://www.aspose.com/.net/pdf-component.aspx"><strong>Aspose.Pdf for .NET</strong></a><br /> <strong>Specializing in:</strong> PDF, PDF/A</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/powerpoint-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_slides-for-net.jpg" alt="Aspose.Slides for .NET" width="60" height="60" /></a></td>
            <td style="padding-left: 8px; vertical-align: top;"><a href="http://www.aspose.com/.net/powerpoint-component.aspx"><strong>Aspose.Slides for .NET</strong></a><br /> <strong>Specializing in:</strong> PPT, POT, PPS, PPTX, POTX, PPSX, ODP, PDF, PDF Notes, XPS, SVG, TIFF and HTML files.</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/barcode-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_barcode-for-net.jpg" alt="Aspose.BarCode for .NET" width="60" height="60" /></a></td>
            <td style="padding-left: 8px; vertical-align: top;"><a href="http://www.aspose.com/.net/barcode-component.aspx"><strong>Aspose.BarCode for .NET</strong></a> <br /> <strong>Specializing in:</strong> Creating and reading (generating and recognizing) over 25 types of the most popular linear, 2D and postal barcode symbologies</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/project-management-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_tasks-for-net.jpg" alt="Aspose.Tasks for .NET" width="60" height="60" /></a></td>
            <td style="padding-left: 8px; vertical-align: top;"><a href="http://www.aspose.com/.net/project-management-component.aspx"><strong>Aspose.Tasks for .NET</strong></a><br /> <strong>Specializing in:</strong> MSG, OFT, MHT, EML, EMLX, PST and OST files, and communication with Microsoft Exchange</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/email-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_email-for-net.jpg" alt="Aspose.Email for .NET" width="60" height="60" /></a></td>
            <td style="padding-left: 8px; vertical-align: top;"><a href="http://www.aspose.com/.net/email-component.aspx"><strong>Aspose.Email for .NET</strong></a><br /> <strong>Specializing in:</strong> MPP/XML, Microsoft Project (2003, 2007, 2010, 2013)</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/diagram-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_diagram-for-net.jpg" alt="Aspose.Diagram for .NET" width="60" height="60" /></a></td>
            <td style="padding-left: 8px; vertical-align: top;"><a href="http://www.aspose.com/.net/diagram-component.aspx"><strong>Aspose.Diagram for .NET</strong></a> <br /> <strong>Specializing in:</strong> VSD/VDX, Microsoft Visio (2007/2010/2013)</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/ocr-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_ocr-for-net.jpg" alt="Aspose.OCR for .NET" width="60" height="60" /></a></td>
            <td style="padding-left: 8px; vertical-align: top;"><a href="http://www.aspose.com/.net/ocr-component.aspx"><strong>Aspose.OCR for .NET</strong></a> <br /> <strong>Specializing in:</strong> Extracting text from images</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/imaging-component.aspx"><img src="http://www.aspose.com/App_Themes/V2/images/productLogos/NET/aspose_imaging-for-net.jpg" alt="Aspose.Imaging for .NET" width="60" height="60" /> </a></td>
            <td style="padding-left: 8px; vertical-align: top;"><a href="http://www.aspose.com/.net/imaging-component.aspx"><strong>Aspose.Imaging for .NET</strong></a> <br /> <strong>Specializing in:</strong> BMP, JPEG, TIFF, GIF, PNG and PSD images</td>
        </tr>
        <tr>
            <td><a href="http://www.aspose.com/.net/imaging-component.aspx"><img src="http://cdn.aspose.com/images/marketplace/aspose_note-for-net.png" alt="Aspose.Imaging for .NET" width="60" height="60" /> </a></td>
            <td style="padding-left: 8px; vertical-align: top;"><a href="http://www.aspose.com/.net/imaging-component.aspx"><strong>Aspose.Note for .NET</strong></a> <br /> <strong>Specializing in:</strong> Microsoft OneNote (2010/2013)</td>
        </tr>
    </tbody>
</table>